/* Statements and Expressions
Java statements appear inside methods and classes; they describe all activities of a Java
program. Variable declarations and assignments, such as those in the previous sec‐
tion, are statements, as are basic language structures such as if/then conditionals and
loops. (More on these structures later in this chapter.)
*/
int size = 5;
 if ( size > 10 )
 doSomething();
 for ( int x = 0; x < size; x++ ) { ... }
/*Expressions produce values; an expression is evaluated to produce a result that is to be
used as part of another expression or in a statement. Method calls, object allocations,
and, of course, mathematical expressions are examples of expressions.
 */
new Object()
 Math.sin( 3.1415 )
 42 * 64
